train_dataset_path: "data/MMD_12K_S30_A/"
validation_dataset_path: "data/MMD_12K_TEST/"
k_eig: 128
wks_eig: 256
n_fmap: 100
n_cfmap: 70
training_batch_size: 5
validation_batch_size: 1
C_in: 256
n_feat: 256
lambda: 100
C_width: 512
N_block: 8
mlp_hidden_dims: []
resolvant_gamma: 0.5
robust: true
learning_rate: 0.0001
lr_step_size: 1
lr_gamma: 0.333
total_epochs: 30
start_alpha: 1
final_alpha: 100
save_interval: 100